[workspace]
members = ["crates/*", "nix/reference-tauri-happ"]
resolver = "2"
exclude = [ "examples/end-user-happ", "examples/holochain-runtime", "crates/tauri-plugin-holochain-foreground-service/examples/tauri-app"]
