[package]
name = "holochain_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
# Holochain dependencies
mr_bundle = "0.5.0-rc"
holochain = { version = "0.5.0-rc", features = [ "unstable-functions", "test_utils" ] }
holochain_types = "0.5.0-rc"
holochain_keystore = "0.5.0-rc"
holochain_conductor_api = "0.5.0-rc"

kitsune_p2p_mdns = "0.4"
kitsune2_api = "0.1"
kitsune2_core = "0.1"

sbd-server = "0.1.0"
tx5-signal = "0.3.3"

# Lair dependencies
lair_keystore_api = "0.6.0"
lair_keystore = { version = "0.6.0" }

# Holochain client
holochain_client = "0.7.0-rc"

# Other dependencies
tracing = { version = "0.1", features = ["log", "log-always"] }
rustls = { version = "0.23.25", features = ["ring"] }
arbitrary = "=1.3.2"
derive_arbitrary = "=1.3.2"
url2 = "0.0.6"
thiserror = "1.0"
one_err = "0"
serde = "1.0.193"
portpicker = "0.1"
log = "0.4"
async-std = "1.12"
local-ip-address = "0.6"
async-trait = "0.1"
sha256 = "1"
zip = { version = "0.6" }
serde_json = "1"
base64 = "0.22"
tokio = "1"
anyhow = "1"
